spring:
  server:
    port: 8080
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
